version: '24'

include:
  - ./docker-compose-s3.yaml

services:
  database:
    image: 'postgres:latest'

    environment:
      POSTGRES_USER: ${PW_DB_USER}
      POSTGRES_PASSWORD: ${PW_DB_PASSWORD}
      POSTGRES_DB: ${PW_DB_NAME}

    ports:
      - ${PW_DB_PORT}:5432
